name: smart_refresher
description: pull-to-refresh and infinite loading in Flutter scrollables.
version: 0.1.0
homepage: https://github.com/ampslabs/smart-refresher

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
