name: smart_refresher
description: A powerful Flutter widget providing pull-to-refresh and infinite loading for scrollable content.
version: 0.1.0
homepage: https://github.com/ampslabs/smart-refresher
repository: https://github.com/ampslabs/smart-refresher
issue_tracker: https://github.com/ampslabs/smart-refresher/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
